name: mangopeople.org.in
favicon: null
layout_spectrum: 0.320945
typography_spectrum: 0.440315
title: Mango People
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9783747163671521
  lightness: 0.18942875811789228
  saturation: 0.32337382425266314
  rhythmicContrast: 0.3416627443595571
purpose:
  - name: null
    item: null
    url: null
